apiVersion: apps/v1
kind: Deployment
metadata:
  name: world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
      - name: world
        image: harshakata/world:latest #harshakata is my docker hub username (my-docker-hub-username/world)
        ports:
        - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: world
spec:
  selector:
    app: world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
